mysql:
  db: chatnio
  host: localhost
  password: chatnio123456
  port: 3306
  user: root
  tls: false

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    api_key: ""
    max_results: 5
    topic: general
    depth: basic
    crop: false
    crop_len: 1000
  task:
    model: ""
